### ISSUE TITLE
Authorization is not set via Swagger page

### ISSUE THREAD

**Issue by GoossensMark** [jgelon/LoanApplication-BE#41]
When executing a request via the Swagger UI AND a valid token value is set. a 401 is returned from BE. This is because in the actual request send from the browser, in the header no Authorization parameter is set. See attached scr. 

![image](https://user-images.githubusercontent.com/18330130/196937989-f4a73bd9-bc6f-48f9-bd05-1ba8c16f6b3b.png)

This seems to happen for every request in the swagger which is used. I tried figuring out where this could be going wrong in the code and it seems to be happening in:

BaseControllerTest.java in line 29. 
this.mockMvc.perform(post("/secure").header("Authorization", "Bearer Fake")).andDo(print()).andExpect(status().isOk())

It seems to me that Bearer Fake seems wrong

**Comment by jgelon** [comment]
You need to call the authorization API first to get your proper token.

The Bearer Fake authorization is for unittesting only ;)
